"""legacy wms schema baseline

Revision ID: 20260820_00
Revises:
Create Date: 2026-08-20 09:38:43.087429
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '20260820_00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True, comment='配置项名称'),
    sa.Column('value', sa.String(length=500), nullable=True, comment='配置项值'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='配置项描述'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_id'), 'config', ['id'], unique=False)
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=True)
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True, comment='货物条码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='货物名称'),
    sa.Column('spec', sa.String(length=100), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_barcode'), 'goods', ['barcode'], unique=True)
    op.create_index(op.f('ix_goods_id'), 'goods', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=100), nullable=True, comment='加密密码'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='真实姓名'),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', name='userrole'), nullable=True, comment='角色'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_ldap_user', sa.Boolean(), nullable=True, comment='是否是LDAP用户'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('current_warehouse_id', sa.Integer(), nullable=True, comment='当前选择的仓库ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='仓库编码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='仓库名称'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='仓库地址'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('check_order_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True, comment='盘点单号'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: DRAFT-草稿, IN_PROGRESS-盘点中, COMPLETED-已完成'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('complete_time', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_order_header_id'), 'check_order_header', ['id'], unique=False)
    op.create_index(op.f('ix_check_order_header_order_no'), 'check_order_header', ['order_no'], unique=True)
    op.create_table('inbound_order_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True, comment='入库单号'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('supplier', sa.String(length=200), nullable=True, comment='供应商'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('total_amount', sa.Float(), nullable=True, comment='总金额'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('complete_time', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_header_id'), 'inbound_order_header', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_order_header_order_no'), 'inbound_order_header', ['order_no'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='所属仓库ID'),
    sa.Column('location_code', sa.String(length=50), nullable=True, comment='库位编码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='库位名称'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_location_code'), 'locations', ['location_code'], unique=True)
    op.create_table('outbound_order_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True, comment='出库单号'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('customer', sa.String(length=200), nullable=True, comment='客户'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('total_amount', sa.Float(), nullable=True, comment='总金额'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('complete_time', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_header_id'), 'outbound_order_header', ['id'], unique=False)
    op.create_index(op.f('ix_outbound_order_header_order_no'), 'outbound_order_header', ['order_no'], unique=True)
    op.create_table('user_warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认仓库'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_warehouses_id'), 'user_warehouses', ['id'], unique=False)
    op.create_table('check_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=True, comment='单据头ID'),
    sa.Column('goods_id', sa.Integer(), nullable=True, comment='货物ID'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='库位ID'),
    sa.Column('check_quantity', sa.Float(), nullable=True, comment='盘点数量'),
    sa.Column('actual_quantity', sa.Float(), nullable=True, comment='系统库存数量'),
    sa.Column('diff_quantity', sa.Float(), nullable=True, comment='差异数量'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['header_id'], ['check_order_header.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_order_item_id'), 'check_order_item', ['id'], unique=False)
    op.create_table('check_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('goods_id', sa.Integer(), nullable=True, comment='货物ID'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='库位ID'),
    sa.Column('check_quantity', sa.Float(), nullable=True, comment='盘点数量'),
    sa.Column('actual_quantity', sa.Float(), nullable=True, comment='实际库存数量'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_records_id'), 'check_records', ['id'], unique=False)
    op.create_table('inbound_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=True, comment='单据头ID'),
    sa.Column('goods_id', sa.Integer(), nullable=True, comment='货物ID'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='库位ID'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='数量'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('total_price', sa.Float(), nullable=True, comment='总价'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['header_id'], ['inbound_order_header.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_item_id'), 'inbound_order_item', ['id'], unique=False)
    op.create_table('inventory_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('goods_id', sa.Integer(), nullable=True, comment='货物ID'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='库位ID'),
    sa.Column('type', sa.Enum('IN', 'OUT', name='inventorytype'), nullable=True, comment='类型：入库/出库'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='数量'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_records_id'), 'inventory_records', ['id'], unique=False)
    op.create_table('outbound_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=True, comment='单据头ID'),
    sa.Column('goods_id', sa.Integer(), nullable=True, comment='货物ID'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='库位ID'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='数量'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('total_price', sa.Float(), nullable=True, comment='总价'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['header_id'], ['outbound_order_header.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_item_id'), 'outbound_order_item', ['id'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('goods_id', sa.Integer(), nullable=True, comment='货物ID'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='库位ID'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='库存数量'),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'goods_id', 'location_id', name='_warehouse_goods_location_uc')
    )
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_outbound_order_item_id'), table_name='outbound_order_item')
    op.drop_table('outbound_order_item')
    op.drop_index(op.f('ix_inventory_records_id'), table_name='inventory_records')
    op.drop_table('inventory_records')
    op.drop_index(op.f('ix_inbound_order_item_id'), table_name='inbound_order_item')
    op.drop_table('inbound_order_item')
    op.drop_index(op.f('ix_check_records_id'), table_name='check_records')
    op.drop_table('check_records')
    op.drop_index(op.f('ix_check_order_item_id'), table_name='check_order_item')
    op.drop_table('check_order_item')
    op.drop_index(op.f('ix_user_warehouses_id'), table_name='user_warehouses')
    op.drop_table('user_warehouses')
    op.drop_index(op.f('ix_outbound_order_header_order_no'), table_name='outbound_order_header')
    op.drop_index(op.f('ix_outbound_order_header_id'), table_name='outbound_order_header')
    op.drop_table('outbound_order_header')
    op.drop_index(op.f('ix_locations_location_code'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_inbound_order_header_order_no'), table_name='inbound_order_header')
    op.drop_index(op.f('ix_inbound_order_header_id'), table_name='inbound_order_header')
    op.drop_table('inbound_order_header')
    op.drop_index(op.f('ix_check_order_header_order_no'), table_name='check_order_header')
    op.drop_index(op.f('ix_check_order_header_id'), table_name='check_order_header')
    op.drop_table('check_order_header')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_goods_id'), table_name='goods')
    op.drop_index(op.f('ix_goods_barcode'), table_name='goods')
    op.drop_table('goods')
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_index(op.f('ix_config_id'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
