"""gsp foundation and controlled receiving

Revision ID: 20260820_01
Revises: 20260820_00
Create Date: 2026-08-20 09:33:21.040823
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '20260820_01'
down_revision: Union[str, None] = '20260820_00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsp_integration_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('message_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsp_integration_outbox_destination'), 'gsp_integration_outbox', ['destination'], unique=False)
    op.create_index(op.f('ix_gsp_integration_outbox_idempotency_key'), 'gsp_integration_outbox', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_gsp_integration_outbox_message_type'), 'gsp_integration_outbox', ['message_type'], unique=False)
    op.create_index(op.f('ix_gsp_integration_outbox_status'), 'gsp_integration_outbox', ['status'], unique=False)
    op.create_table('gsp_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('source_ip', sa.String(length=100), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index(op.f('ix_gsp_audit_events_action'), 'gsp_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_gsp_audit_events_actor_user_id'), 'gsp_audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_gsp_audit_events_entity_id'), 'gsp_audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_gsp_audit_events_entity_type'), 'gsp_audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_gsp_audit_events_occurred_at'), 'gsp_audit_events', ['occurred_at'], unique=False)
    op.create_table('gsp_business_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('partner_type', sa.String(length=20), nullable=False),
    sa.Column('unified_social_credit_code', sa.String(length=50), nullable=True),
    sa.Column('license_no', sa.String(length=100), nullable=False),
    sa.Column('license_scope', sa.Text(), nullable=False),
    sa.Column('license_valid_from', sa.Date(), nullable=True),
    sa.Column('license_valid_to', sa.Date(), nullable=False),
    sa.Column('quality_agreement_valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('suspension_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsp_business_partners_code'), 'gsp_business_partners', ['code'], unique=True)
    op.create_index(op.f('ix_gsp_business_partners_license_valid_to'), 'gsp_business_partners', ['license_valid_to'], unique=False)
    op.create_index(op.f('ix_gsp_business_partners_name'), 'gsp_business_partners', ['name'], unique=False)
    op.create_index(op.f('ix_gsp_business_partners_partner_type'), 'gsp_business_partners', ['partner_type'], unique=False)
    op.create_index(op.f('ix_gsp_business_partners_status'), 'gsp_business_partners', ['status'], unique=False)
    op.create_index(op.f('ix_gsp_business_partners_unified_social_credit_code'), 'gsp_business_partners', ['unified_social_credit_code'], unique=False)
    op.create_table('gsp_drug_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.Column('approval_no', sa.String(length=100), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=False),
    sa.Column('dosage_form', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('marketing_authorization_holder', sa.String(length=200), nullable=True),
    sa.Column('storage_condition', sa.String(length=30), nullable=False),
    sa.Column('min_temperature', sa.Float(), nullable=True),
    sa.Column('max_temperature', sa.Float(), nullable=True),
    sa.Column('is_prescription', sa.Boolean(), nullable=False),
    sa.Column('is_special_controlled', sa.Boolean(), nullable=False),
    sa.Column('traceability_required', sa.Boolean(), nullable=False),
    sa.Column('registration_valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsp_drug_profiles_approval_no'), 'gsp_drug_profiles', ['approval_no'], unique=True)
    op.create_index(op.f('ix_gsp_drug_profiles_goods_id'), 'gsp_drug_profiles', ['goods_id'], unique=True)
    op.create_index(op.f('ix_gsp_drug_profiles_status'), 'gsp_drug_profiles', ['status'], unique=False)
    op.create_table('gsp_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_gsp_user_role')
    )
    op.create_index(op.f('ix_gsp_role_assignments_role'), 'gsp_role_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_gsp_role_assignments_user_id'), 'gsp_role_assignments', ['user_id'], unique=False)
    op.create_table('gsp_drug_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('receipt_document_no', sa.String(length=100), nullable=False),
    sa.Column('inspection_report_no', sa.String(length=100), nullable=True),
    sa.Column('traceability_code', sa.String(length=200), nullable=True),
    sa.Column('arrival_temperature', sa.Float(), nullable=True),
    sa.Column('transport_temperature_min', sa.Float(), nullable=True),
    sa.Column('transport_temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_record_ref', sa.String(length=500), nullable=True),
    sa.Column('acceptance_conclusion', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['gsp_business_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goods_id', 'batch_no', name='uq_gsp_goods_batch')
    )
    op.create_index(op.f('ix_gsp_drug_batches_batch_no'), 'gsp_drug_batches', ['batch_no'], unique=False)
    op.create_index(op.f('ix_gsp_drug_batches_expiry_date'), 'gsp_drug_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_gsp_drug_batches_goods_id'), 'gsp_drug_batches', ['goods_id'], unique=False)
    op.create_index(op.f('ix_gsp_drug_batches_status'), 'gsp_drug_batches', ['status'], unique=False)
    op.create_index(op.f('ix_gsp_drug_batches_supplier_id'), 'gsp_drug_batches', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_gsp_drug_batches_traceability_code'), 'gsp_drug_batches', ['traceability_code'], unique=False)
    op.create_table('gsp_partner_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('file_ref', sa.String(length=500), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['gsp_business_partners.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'document_type', 'document_no', name='uq_gsp_partner_document')
    )
    op.create_index(op.f('ix_gsp_partner_documents_partner_id'), 'gsp_partner_documents', ['partner_id'], unique=False)
    op.create_index(op.f('ix_gsp_partner_documents_valid_to'), 'gsp_partner_documents', ['valid_to'], unique=False)
    op.create_table('gsp_purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('ordered_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('quality_approved_by', sa.Integer(), nullable=True),
    sa.Column('quality_approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quality_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['gsp_business_partners.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsp_purchase_orders_order_no'), 'gsp_purchase_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_gsp_purchase_orders_status'), 'gsp_purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_gsp_purchase_orders_supplier_id'), 'gsp_purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_gsp_purchase_orders_warehouse_id'), 'gsp_purchase_orders', ['warehouse_id'], unique=False)
    op.create_table('gsp_batch_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('stock_status', sa.String(length=30), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_gsp_batch_stock_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['batch_id'], ['gsp_drug_batches.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'warehouse_id', 'location_id', name='uq_gsp_batch_location')
    )
    op.create_index(op.f('ix_gsp_batch_stock_batch_id'), 'gsp_batch_stock', ['batch_id'], unique=False)
    op.create_index(op.f('ix_gsp_batch_stock_location_id'), 'gsp_batch_stock', ['location_id'], unique=False)
    op.create_index(op.f('ix_gsp_batch_stock_stock_status'), 'gsp_batch_stock', ['stock_status'], unique=False)
    op.create_index(op.f('ix_gsp_batch_stock_warehouse_id'), 'gsp_batch_stock', ['warehouse_id'], unique=False)
    op.create_table('gsp_purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.CheckConstraint('ordered_quantity > 0', name='ck_gsp_po_item_ordered_positive'),
    sa.CheckConstraint('received_quantity <= ordered_quantity', name='ck_gsp_po_item_received_not_over'),
    sa.CheckConstraint('received_quantity >= 0', name='ck_gsp_po_item_received_nonnegative'),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['gsp_purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'line_no', name='uq_gsp_po_line')
    )
    op.create_index(op.f('ix_gsp_purchase_order_items_goods_id'), 'gsp_purchase_order_items', ['goods_id'], unique=False)
    op.create_index(op.f('ix_gsp_purchase_order_items_purchase_order_id'), 'gsp_purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('gsp_quality_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('initiated_by', sa.Integer(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('released_by', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('release_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['gsp_drug_batches.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsp_quality_holds_batch_id'), 'gsp_quality_holds', ['batch_id'], unique=False)
    op.create_index(op.f('ix_gsp_quality_holds_status'), 'gsp_quality_holds', ['status'], unique=False)
    op.create_table('gsp_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=100), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_document_no', sa.String(length=100), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['gsp_purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsp_receipts_delivery_document_no'), 'gsp_receipts', ['delivery_document_no'], unique=False)
    op.create_index(op.f('ix_gsp_receipts_purchase_order_id'), 'gsp_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_gsp_receipts_receipt_no'), 'gsp_receipts', ['receipt_no'], unique=True)
    op.create_index(op.f('ix_gsp_receipts_status'), 'gsp_receipts', ['status'], unique=False)
    op.create_table('gsp_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('inspection_status', sa.String(length=30), nullable=False),
    sa.Column('inspection_conclusion', sa.String(length=500), nullable=True),
    sa.Column('inspection_report_no', sa.String(length=100), nullable=True),
    sa.Column('traceability_code', sa.String(length=200), nullable=True),
    sa.Column('arrival_temperature', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('transport_temperature_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('transport_temperature_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature_record_ref', sa.String(length=500), nullable=True),
    sa.Column('inspected_by', sa.Integer(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('accepted_quantity + rejected_quantity <= received_quantity', name='ck_gsp_receipt_inspected_not_over'),
    sa.CheckConstraint('accepted_quantity >= 0', name='ck_gsp_receipt_accepted_nonnegative'),
    sa.CheckConstraint('received_quantity > 0', name='ck_gsp_receipt_received_positive'),
    sa.CheckConstraint('rejected_quantity >= 0', name='ck_gsp_receipt_rejected_nonnegative'),
    sa.ForeignKeyConstraint(['batch_id'], ['gsp_drug_batches.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['gsp_purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['gsp_receipts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id', 'purchase_order_item_id', 'batch_id', name='uq_gsp_receipt_po_item_batch')
    )
    op.create_index(op.f('ix_gsp_receipt_items_batch_id'), 'gsp_receipt_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_gsp_receipt_items_inspection_status'), 'gsp_receipt_items', ['inspection_status'], unique=False)
    op.create_index(op.f('ix_gsp_receipt_items_location_id'), 'gsp_receipt_items', ['location_id'], unique=False)
    op.create_index(op.f('ix_gsp_receipt_items_purchase_order_item_id'), 'gsp_receipt_items', ['purchase_order_item_id'], unique=False)
    op.create_index(op.f('ix_gsp_receipt_items_receipt_id'), 'gsp_receipt_items', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_gsp_receipt_items_traceability_code'), 'gsp_receipt_items', ['traceability_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsp_receipt_items_traceability_code'), table_name='gsp_receipt_items')
    op.drop_index(op.f('ix_gsp_receipt_items_receipt_id'), table_name='gsp_receipt_items')
    op.drop_index(op.f('ix_gsp_receipt_items_purchase_order_item_id'), table_name='gsp_receipt_items')
    op.drop_index(op.f('ix_gsp_receipt_items_location_id'), table_name='gsp_receipt_items')
    op.drop_index(op.f('ix_gsp_receipt_items_inspection_status'), table_name='gsp_receipt_items')
    op.drop_index(op.f('ix_gsp_receipt_items_batch_id'), table_name='gsp_receipt_items')
    op.drop_table('gsp_receipt_items')
    op.drop_index(op.f('ix_gsp_receipts_status'), table_name='gsp_receipts')
    op.drop_index(op.f('ix_gsp_receipts_receipt_no'), table_name='gsp_receipts')
    op.drop_index(op.f('ix_gsp_receipts_purchase_order_id'), table_name='gsp_receipts')
    op.drop_index(op.f('ix_gsp_receipts_delivery_document_no'), table_name='gsp_receipts')
    op.drop_table('gsp_receipts')
    op.drop_index(op.f('ix_gsp_quality_holds_status'), table_name='gsp_quality_holds')
    op.drop_index(op.f('ix_gsp_quality_holds_batch_id'), table_name='gsp_quality_holds')
    op.drop_table('gsp_quality_holds')
    op.drop_index(op.f('ix_gsp_purchase_order_items_purchase_order_id'), table_name='gsp_purchase_order_items')
    op.drop_index(op.f('ix_gsp_purchase_order_items_goods_id'), table_name='gsp_purchase_order_items')
    op.drop_table('gsp_purchase_order_items')
    op.drop_index(op.f('ix_gsp_batch_stock_warehouse_id'), table_name='gsp_batch_stock')
    op.drop_index(op.f('ix_gsp_batch_stock_stock_status'), table_name='gsp_batch_stock')
    op.drop_index(op.f('ix_gsp_batch_stock_location_id'), table_name='gsp_batch_stock')
    op.drop_index(op.f('ix_gsp_batch_stock_batch_id'), table_name='gsp_batch_stock')
    op.drop_table('gsp_batch_stock')
    op.drop_index(op.f('ix_gsp_purchase_orders_warehouse_id'), table_name='gsp_purchase_orders')
    op.drop_index(op.f('ix_gsp_purchase_orders_supplier_id'), table_name='gsp_purchase_orders')
    op.drop_index(op.f('ix_gsp_purchase_orders_status'), table_name='gsp_purchase_orders')
    op.drop_index(op.f('ix_gsp_purchase_orders_order_no'), table_name='gsp_purchase_orders')
    op.drop_table('gsp_purchase_orders')
    op.drop_index(op.f('ix_gsp_partner_documents_valid_to'), table_name='gsp_partner_documents')
    op.drop_index(op.f('ix_gsp_partner_documents_partner_id'), table_name='gsp_partner_documents')
    op.drop_table('gsp_partner_documents')
    op.drop_index(op.f('ix_gsp_drug_batches_traceability_code'), table_name='gsp_drug_batches')
    op.drop_index(op.f('ix_gsp_drug_batches_supplier_id'), table_name='gsp_drug_batches')
    op.drop_index(op.f('ix_gsp_drug_batches_status'), table_name='gsp_drug_batches')
    op.drop_index(op.f('ix_gsp_drug_batches_goods_id'), table_name='gsp_drug_batches')
    op.drop_index(op.f('ix_gsp_drug_batches_expiry_date'), table_name='gsp_drug_batches')
    op.drop_index(op.f('ix_gsp_drug_batches_batch_no'), table_name='gsp_drug_batches')
    op.drop_table('gsp_drug_batches')
    op.drop_index(op.f('ix_gsp_role_assignments_user_id'), table_name='gsp_role_assignments')
    op.drop_index(op.f('ix_gsp_role_assignments_role'), table_name='gsp_role_assignments')
    op.drop_table('gsp_role_assignments')
    op.drop_index(op.f('ix_gsp_drug_profiles_status'), table_name='gsp_drug_profiles')
    op.drop_index(op.f('ix_gsp_drug_profiles_goods_id'), table_name='gsp_drug_profiles')
    op.drop_index(op.f('ix_gsp_drug_profiles_approval_no'), table_name='gsp_drug_profiles')
    op.drop_table('gsp_drug_profiles')
    op.drop_index(op.f('ix_gsp_business_partners_unified_social_credit_code'), table_name='gsp_business_partners')
    op.drop_index(op.f('ix_gsp_business_partners_status'), table_name='gsp_business_partners')
    op.drop_index(op.f('ix_gsp_business_partners_partner_type'), table_name='gsp_business_partners')
    op.drop_index(op.f('ix_gsp_business_partners_name'), table_name='gsp_business_partners')
    op.drop_index(op.f('ix_gsp_business_partners_license_valid_to'), table_name='gsp_business_partners')
    op.drop_index(op.f('ix_gsp_business_partners_code'), table_name='gsp_business_partners')
    op.drop_table('gsp_business_partners')
    op.drop_index(op.f('ix_gsp_audit_events_occurred_at'), table_name='gsp_audit_events')
    op.drop_index(op.f('ix_gsp_audit_events_entity_type'), table_name='gsp_audit_events')
    op.drop_index(op.f('ix_gsp_audit_events_entity_id'), table_name='gsp_audit_events')
    op.drop_index(op.f('ix_gsp_audit_events_actor_user_id'), table_name='gsp_audit_events')
    op.drop_index(op.f('ix_gsp_audit_events_action'), table_name='gsp_audit_events')
    op.drop_table('gsp_audit_events')
    op.drop_index(op.f('ix_gsp_integration_outbox_status'), table_name='gsp_integration_outbox')
    op.drop_index(op.f('ix_gsp_integration_outbox_message_type'), table_name='gsp_integration_outbox')
    op.drop_index(op.f('ix_gsp_integration_outbox_idempotency_key'), table_name='gsp_integration_outbox')
    op.drop_index(op.f('ix_gsp_integration_outbox_destination'), table_name='gsp_integration_outbox')
    op.drop_table('gsp_integration_outbox')
    # ### end Alembic commands ###
